name: Style and Testing
on: push

jobs:
  check-style:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install tools
        run: python -m pip install --upgrade pip pycodestyle

      - name: Check Style
        run: pycodestyle --first *.py

      - name: Install tools
        run: python -m pip install --upgrade pip pytest

      - name: Install pyyoutube
        run: python -m pip install --upgrade pip python-youtube

      - name: Install SQLAlchemy
        run: python -m pip install --upgrade pip SQLAlchemy

      - name: Install pandas
        run: python -m pip install --upgrade pip pandas

      - name: Test with pytest
        run: |
          python3 -m unittest youtubeTest.py